### ISSUE TITLE
Background image overfills the box

### ISSUE THREAD

**Issue by iamjameshannam** [jneilliii/OctoPrint-CustomBackground#10]
The first version had great scaling for the image, the uploaded image seemed to resize to fit the window. This version, the image is HUGE, off the page....

**Comment by jneilliii** [comment]
The first version actually had no scaling at all set. The latest update
changed the fill method to better size the image. Maybe it's working for me
because I'm using the cyborg theme. Are you using a url, or file upload?

**Comment by jneilliii** [comment]
Also, what browser are you using?

**Comment by jneilliii** [comment]
I've updated to version 0.5.0 that allows you to control the background-size property.  If you set it to auto it will be back to the way it was prior to version 0.4.0.

**Comment by iamjameshannam** [comment]
Hi!

Im using the file upload, the new version youve done works perfectly!!!

Awsome job sir!!!

James



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=thelearnmaker@gmail.com&idSignature=22>

**Comment by jneilliii** [comment]
cool, thanks for the feedback.
