### ISSUE TITLE
Not Displaying Image

### ISSUE THREAD

**Issue by xstrex** [jneilliii/OctoPrint-CustomBackground#16]
Just updated to 0.6.0, loaded up the UI (with the plugin installed). Uploaded an image via built-in file browser, page reloads, but image doesn't replace graph background. Tried 3x different jpg's, none of them work.

**Comment by jneilliii** [comment]
Can you upload your octoprint.log please?

**Comment by xstrex** [comment]
Yea, np, I'll get it uploaded when I get home.

**Comment by xstrex** [comment]
Wow, totally forgot to upload it. Here ya go.. the relevant lines anyways: 

> 2017-10-08 02:40:40,073 - octoprint.plugins.custombackground - INFO - Setting background url for octopi-bg.jpg
> 2017-10-08 02:40:40,079 - octoprint.plugins.custombackground - INFO - /home/pi/.octoprint/data/custombackground/uploaded.jpg

Octoprint UI reloads, but background stays the same.

**Comment by jneilliii** [comment]
The log indicates the background is being saved, Do you have the tempsgraph plugin installed?  There is a conflict with that plugin I know that makes the image not show up. Also, what browser are you using?
