### ISSUE TITLE
Can'r figure out how to change image

### ISSUE THREAD

**Issue by x9x9x9x9x9** [jneilliii/OctoPrint-CustomBackground#17]
When I installed this plugin it was very simple to add a background. Now I ant to change the image but can't figure out how to upload it. It says store locally but how? just upload as if its a code file? If I have to use putty then this is a downgrade.

**Comment by jneilliii** [comment]
Yes, you still just upload as if it's a gcode file in the latest version. It just allows you to delete that file from the file manager without effecting the background.
