### ISSUE TITLE
[PLUGIN CONFLICT] with TouchUI plugin...

### ISSUE THREAD

**Issue by bolsoncerrado** [jneilliii/OctoPrint-CustomBackground#18]
https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/154

**Comment by jneilliii** [comment]
TouchUI changes the default background-image css property to a different element then the default install.  Billy is looking into fixing it on his end.

**Comment by BillyBlaze** [comment]
@jneilliii this is fixed in the upcoming release, however could you perhaps on your end reset the `background-position` property? currently you inherit this, but TouchUI is changing it, so you inherit that from TouchUI.

**Comment by BillyBlaze** [comment]
By default OctoPrint is ```background-position: center;``` but perhaps it can be helpfull for people to set their own?

**Comment by jneilliii** [comment]
good point.  just released new version with that option.

**Comment by bolsoncerrado** [comment]
Seems now we have a complete MIX instead :D 
https://i.imgur.com/BBQmVIZ.png

**Comment by jneilliii** [comment]
I'm updating both plugins now on my pi and will see what might be going on.  By chance did you do a ctrl+f5 to reload outside of cache?

**Comment by BillyBlaze** [comment]
Hmm, seems like TouchUI hasn't recompiled your CSS. Can you change colour and set it back to yours? That would force to recompile it.

**Comment by jneilliii** [comment]
Thanks Billy, I just installed the updated for both plugins on my production pi and it seems to be working in chrome on a full desktop.

**Comment by bolsoncerrado** [comment]
I think it has to do with the AUTO setting.... I have two printers with the newest versions of pi+plugins and both show different behaviours, once of the two being correct.

**Comment by bolsoncerrado** [comment]
Hmmm correct one reads "Contain" and "Center"

The incorrect one reads "Cover" and "Center Center"
