### ISSUE TITLE
Needs alpha transparency setting

### ISSUE THREAD

**Issue by robertbl22** [jneilliii/OctoPrint-CustomBackground#19]
Would be helpful to be able to set the image transparency because most images interfere with the readability of the graph. Thanks for the great plugin!

**Comment by jneilliii** [comment]
I looked into this and it seems that with the current implementation there is no way to set an opacity/transparency value to background images of elements.  You can however, use a translucent png file and that will work for what you are trying to do.  The original OctoPrint image is that way, see below.  You can use free tools like GIMP to be able to accomplish this.

![image](https://user-images.githubusercontent.com/5249455/38753621-faadc21c-3f2c-11e8-8a82-4eecc9784f7a.png)
