### ISSUE TITLE
[REQUEST] Change BRAND icon on the upper left 

### ISSUE THREAD

**Issue by bolsoncerrado** [jneilliii/OctoPrint-CustomBackground#20]
Can you add the option to change the icon on the upper left, aka "brand" icon, too?

in packedcore CSS:

#navbar

....

 .brand span {
    **background-image: url(../img/tentacle-20x20-light.png);**
}

**Comment by jneilliii** [comment]
You may want to look into [OctoPrint-Themify Plugin](https://github.com/Birkbjo/OctoPrint-Themeify).  It allows full customization of the UI through css.  I just tested and if you use the selector `#navbar .navbar-inner .brand span` and set the value to `url(https://lh3.googleusercontent.com/5Gekwg12zc-foOjLzpBzeZiAC2yMg1LlkX7pPF588febneh8kRuvQk0oHfspsEs8Wno=w300)` the branding icon changes.

**Comment by bolsoncerrado** [comment]
While that is far more than acceptable, a simple "icon url" field in the admin interface /settings/ would be awesome ;)

**Comment by amrithmmh** [comment]
i gave url(file:///home/pi/icon.png) instead of https link but my image is not displayed...
can you help please

**Comment by jneilliii** [comment]
Just upload your image as if you were uploading gcode.

**Comment by amrithmmh** [comment]
thanks @jneilliii how to change the favicon/shortcut icon(on the title bar)?

**Comment by jneilliii** [comment]
My plugin doesn't do that... yet.

**Comment by jneilliii** [comment]
Newest version 0.9.0 allows for changing the brand icon.  You will want to resize the image to 20x20 prior to upload and it has to be named icon to be recognized correctly.

**Comment by amrithmmh** [comment]
latest 1.3.9 it no longer works

**Comment by jneilliii** [comment]
I have 1.3.9 and it's working for me fine. You uploaded the file with a name of icon?

![image](https://user-images.githubusercontent.com/5249455/46576098-96f65600-c990-11e8-903c-6f029c1a6ecd.png)

**Comment by amrithmmh** [comment]
yes it worked with your plugin...i tried with themify it doesnt work now..
for any one who needs to change the brand icon
1.use "upload" from octoprint web interface [just like you upload gcode files] and upload "icon.png" file 
that should do the trick.

thank you @jneilliii

**Comment by amrithmmh** [comment]
what should be the name of file for the graph-background?
is it graph-background.png?

**Comment by jneilliii** [comment]
From memory I don't think it has to be named special, just be an image.
