### ISSUE TITLE
Does not work with X-Script-Name

### ISSUE THREAD

**Issue by goofdad** [jneilliii/OctoPrint-CustomBackground#21]
My octoprint coexists with other websites and therefore uses the X-Script-Name so my CR-10 is at myprinters.local/cr-10, my printrbot at myprinters.local/printrbot.

However, when I use this plugin it sets the background to myprinters.local/plugin/custombackground/uploaded.jpg instead of myprinters.local/printrbot/plugin/custombackground/uploaded.jpg.

If I manually go in and edit it it works, but that kindof defeats the purpose :)

**Comment by jneilliii** [comment]
I'll look into that for you.  Is there instructions somewhere that I can reference for configuring mine the same as yours with multiple printers? I'm not familiar with the X-Script-Name reference.

**Comment by goofdad** [comment]
Here's a simplified version of my haproxy config. This points to a local webserver on port 4321, a local webcam in the standard place, and local octoprint server behind /hypercube.

[haproxy.zip](https://github.com/jneilliii/OctoPrint-CustomBackground/files/1545304/haproxy.zip)

**Comment by goofdad** [comment]
You don't need the webserver to be running for the haproxy.cfg to work (it'll just return 404).

**Comment by jneilliii** [comment]
I don't even think I'll need to set it up.  I just made a change in the dev branch that will set the url to a relative path instead of starting with /plugin it should start with plugin.  If you don't mind giving it a try that would be great. Install from url below.

https://github.com/jneilliii/OctoPrint-CustomBackground/archive/dev.zip

**Comment by jneilliii** [comment]
Curious, does the file save from the two different paths correctly into the separate instances of OctoPrint you have running or does the last one overwrite on the server for all url paths?

**Comment by goofdad** [comment]
You need two full separate servers running in different ".octoprint" directories and on different ports, but yes it saves things properly.

**Comment by jneilliii** [comment]
Cool.  Let me know how that relative url change works out.  You'll have to re-upload the image for it to adjust the settings for the url, but in theory it should work.

**Comment by goofdad** [comment]
yep. I'm installing the dev version now. I'll report back in <10 minutes :)

**Comment by goofdad** [comment]
Sorry ... no luck. Still put the wrong url in the config.yaml.

**Comment by jneilliii** [comment]
Ok, I'll do some testing on my end.  I see how it needs to work looking at your haproxy config.

**Comment by jneilliii** [comment]
Quick question on your config.yaml.  Did you set the prefixHeader setting in the server > reverseProxy section?

**Comment by goofdad** [comment]
I didn't need to. It defaults to X-Script-Name

**Comment by jneilliii** [comment]
Ok, I think I've hacked together a fix.  Instead of relative it uses the the url from the browser as a base and then appends the setting to the end of that.  I tested by copying your haproxy.cfg you sent into my pi and restarted everything and installed the updated dev branch linked earlier.  Once you upload your image now, it should work as expected.

**Comment by jneilliii** [comment]
Just realized one caveat with current dev branch implementation.  You have to include the / at the end of your url so you would go to http://myprinters.local/hypercube/ and not http://myprinters.local/hypercube

**Comment by jneilliii** [comment]
I think I got the url pathing straightened out now.  Try from the update 0.8.0 branch, linked below, should work with either http://myprinters.local/hypercube/ or http://myprinters.local/hypercube or http://myprinters.local/hypercube/some_other_path, etc.

https://github.com/jneilliii/OctoPrint-CustomBackground/archive/0.8.0.zip

**Comment by goofdad** [comment]
Awesome! It works!
Thanks!

Side question: is there a "octoprint plugit devs" group somewhere where I could ask a question or three about how to do something? Thanks!

**Comment by jneilliii** [comment]
Cool.  I'll merge that and release to master shortly.  As to your side question, I typically go to the [google group](https://groups.google.com/forum/#!forum/octoprint) for my questions.  Typically either Gina or Mark typically respond over there with good direction on questions. The most traction you'd probably get in [IRC](irc://chat.freenode.net/octoprint), but I haven't gotten into all of that yet.
