### ISSUE TITLE
change background

### ISSUE THREAD

**Issue by fred2088** [jneilliii/OctoPrint-CustomBackground#25]
change background work well from chrome and it display correctly ....
but the IE11 show only the orginal logo only

**Comment by jneilliii** [comment]
It is working for me fine in Internet Explorer 11.  Have you tried pressing ctrl+f5 to force a cache reload?

![image](https://user-images.githubusercontent.com/5249455/36711199-21148798-1b50-11e8-8f21-bb3e6a9744fa.png)

**Comment by fred2088** [comment]
Test again ...
IE11 on 3 PC (2 Win 7, 1 Win 10) can't display custom logo which is chinese windows
chrome and EDGE without problem on all pc

**Comment by jneilliii** [comment]
That's very odd.  I am unable to reproduce this issue so it will be hard for me to debug the problem.

**Comment by jneilliii** [comment]
Just tried from my work machine in IE11 and it works here too.  Are there any errors in the developer tools console on yours?
