### ISSUE TITLE
OctoPrint Temperature tab's font type

### ISSUE THREAD

**Issue by Thisismydigitalself** [jneilliii/OctoPrint-CustomBackground#27]
I use this plugin in both my Pi's and lovin it. please address the following:
https://github.com/foosel/OctoPrint/issues/2567

Thank you.

**Comment by jneilliii** [comment]
@foosel: I'm looking into this and it seems that the temperature graph text is drawn on a canvas and not directly addressable with css selectors to be able to programmatically change the colors. Could you point me in the direction of where in your code the graph is adding that text and any insight as to how a plugin would be able to modify that would be greatly appreciated.

**Comment by foosel** [comment]
The legend is a div laid over the graph, so *that* you could actually adjust through CSS. And that's what I actually thought what the ticket above was about. 

Didn't think of the ticks 🤦 Those are indeed defined in flot itself. It might be possible to control styling a bit through the flot graph options that are defined [here](https://github.com/foosel/OctoPrint/blob/c55c568bbddf5112facf6aa3a173d500936b6cbf/src/octoprint/static/js/app/viewmodels/temperature.js#L319). Would be somewhat invasive to modify though. I guess I'll need to add some kind of callback or something for this to be possible without monkey patching. Will reopen the above mentioned ticket.

**Comment by fastasfast** [comment]
Very newby here. I have installed you OctoPrint-CustomBackground but I can not figure out where to place the gif file in my octoprint pi directory. Thank you for any help.
Jeff

**Comment by jneilliii** [comment]
@fastasfast You just upload your file to OctoPrint like you do for gcode files.

**Comment by fastasfast** [comment]
Worked prefect!
Thank you very much!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
