### ISSUE TITLE
"Upload failed" uploading image file to OctoPrint

### ISSUE THREAD

**Issue by aderusha** [jneilliii/OctoPrint-CustomBackground#29]
When I drag a PNG into OctoPrint to upload locally (meaning, select file in an Explorer window, drag to the left side of the OctoPrint web page in Chrome to "Upload Locally"), an error is shown with the text:

> Could not upload the file. Make sure that it is a valid file with one of these extensions: .g, .gco, .gcode, .stl

https://i.imgur.com/LH9M3uN.png

**Comment by jneilliii** [comment]
Is the extension of the file literally all caps?

**Comment by aderusha** [comment]
The filename I attempted to upload is `800x600_Transparent_Background.png`, as shown in the error dialog screenshot above.  Just tried renaming to `test.png`, same result.  The error is pretty clear about what it's expecting.  Uploading STLs through the same mechanism works as it says.

**Comment by jneilliii** [comment]
That's odd. I'll have to go back and check but i'm pretty sure png files are supported once the plugin is installed.

**Comment by jneilliii** [comment]
So I just tried on my OctoPrint 1.3.10 running on OctoPi 0.15.1 and it's working fine for me. Are there any errors in your ocotprint.log file?

**Comment by aderusha** [comment]
No errors are logged outside of the message shown in the dialog, which clearly indicates it's unhappy with image files being uploaded.  I also have another OctoPrint server that was installed a few years ago and regularly upgraded which does not exhibit this behavior - it only appears on a fresh installation.

**Comment by LazaroFilm** [comment]
Have you tried with another image? It could be your image that is corrupt.

**Comment by aderusha** [comment]
I've resolved this problem with the "UploadAnything" plugin available in the OctoPrint plugin manager.  This plugin allows PNGs to the list of allowed filetypes and now everything works as expected.  

@jneilliii I think this behavior is a new default.  If you can, try a fresh raspbian + octoprint installation and you'll see this error.  The 2 octoprint installations I had installed a year or more ago and have updated along the way don't have this restriction, but a new installation does.  New users will need to utilize a plugin or some other means of disabling the restriction which prevents uploading PNGs before using CustomBackground.

**Comment by jneilliii** [comment]
Quick question, was the file that you were uploading have all caps `PNG` or were they lowercase?  From the function [here](https://github.com/jneilliii/OctoPrint-CustomBackground/blob/6bf3062958cbd08d29129553f4f7f3fd69559aad/octoprint_custombackground/__init__.py#L25) in the code png files are allowed. Maybe its the difference between machinecode versus model being returned, although that shouldn't make a difference. The UploadAnything plugin works the same way as seen [here](https://github.com/rlogiacco/UploadAnything/blob/18a4c075f1856aa5c83ca74e40835b89142882b7/octoprint_uploadanything/__init__.py#L24).
