### ISSUE TITLE
Not working for me.

### ISSUE THREAD

**Issue by ZeekWorld** [jneilliii/OctoPrint-CustomBackground#3]
Running Octopi latest version. 
I've used an sftp to upload the attached file. Match file size and ext. Uploaded file to same path, changed the filename on the plugin path to match new picture. The picture does not display.
![davinci](https://user-images.githubusercontent.com/16088952/29847469-0b880a9a-8cd9-11e7-96c6-ad8f63848c36.png)

**Comment by jneilliii** [comment]
Try this method...use the file manager on the left to upload your image, then right-click the download link and copy the shortcut.  Then paste that into the plugin settings.

**Comment by ZeekWorld** [comment]
That worked, thanks.

**Comment by jneilliii** [comment]
Cool.  I'm working on a better option, just have to figure out how to do uploads.

**Comment by jneilliii** [comment]
I've added direct settings update on image upload.  When you upload your image the plugin will automatically set that url and reload the page with new image.  Also, added size control in the plugin settings.

**Comment by Thisismydigitalself** [comment]
No working for me either.
Tried reading a png file from both a folder i have created and also uploading from GUI and reading from uploaded folder - image not loaded.

**Comment by Thisismydigitalself** [comment]
Ok. Found the "Problem".
I was running "Tempsgraph Plugin (0.2.2)" and apparently your plugin cannot override it's background.
