### ISSUE TITLE
[FR] pre-package some backgrounds

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [jneilliii/OctoPrint-CustomBackground#31]
perhaps it would help to include some backgrounds with plugin distribution
i.e. 
1. transparent png
2. few gray scale densities

**Comment by jneilliii** [comment]
Do you happen to have a collection of those images already? It would save me a little time hunting them down if you did.

**Comment by Andrei-Pozolotin** [comment]
1. a coupe I made are attached
[backgrounds.zip](https://github.com/jneilliii/OctoPrint-CustomBackground/files/4736967/backgrounds.zip)

2. perhaps it would be even easier 
to generate backgrounds on the fly inside JS, i.e.:

a) shade selector
https://www.w3schools.com/colors/colors_picker.asp

b) image generator
https://github.com/IjzerenHein/pnglib-es6

**Comment by jneilliii** [comment]
Thanks. Not sure if I would be able to get the generator to work unless it saves the image to the file system, but I'll take a look at what you posted. At the very least, I'll add a select list to the reset button to allow changing between these backgrounds you provided.

**Comment by jneilliii** [comment]
Ok, I think I've got this working but would be great if I could get you to test. I couldn't help myself and had to include a `jneilliii` bundled image. The change now allows you to also switch between bundled images and the custom uploaded one if you so desire. Use the URL below in plugin manager. The previously uploaded image should still be loaded, please verify that when you test as I had to change the image path to implement this change and it should migrate as part of the update process.

https://github.com/jneilliii/OctoPrint-CustomBackground/archive/0.10.2.zip

**Comment by Andrei-Pozolotin** [comment]
1. 0.10.2 works, thank you
2. tested this on android, and it became apparent that more/darker gray scale b/g are needed

**Comment by jneilliii** [comment]
I'll try to bundle in some additional scale options, figured every 10% transparency would probably work.

**Comment by ALittleSlow** [comment]
I recently noticed activity on a CSS customization plugin. Perhaps this is a more general solution to handling background color and image transparency.

**Comment by jneilliii** [comment]
You could definitely use that plugin to change the background url property of the temp graph, just like you have been for a while now with Themeify's advanced customizations.
