### ISSUE TITLE
background not changing after upload

### ISSUE THREAD

**Issue by ALittleSlow** [jneilliii/OctoPrint-CustomBackground#34]
I'm having a strange issue where I upload a .jpg, and on workstations other than mine, the UI reloads and the image refreshes to the new version immediately, but on my workstation the UI reloads but usually (not always) the old image persists. I've tried a forced reload (Ctrl-Shift-R), restarting browser, restarting Octoprint, without success. A random time later, the new image will finally appear on my computer. Seems like a browser cache issue, but if so I expected the forced reload to fix it. 

Google Chrome for Windows
Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by jneilliii** [comment]
That's a strange one as the background is getting updated apparently, but like you said caught in a cache somewhere. Typically a forced refresh would resolve that, but apparently on this one machine it's not. I'll look into adding a cache buster timestamp to the end of the image url to resolve this problem hopefully long-term.
