### ISSUE TITLE
Uploading the file

### ISSUE THREAD

**Issue by JustCryen** [jneilliii/OctoPrint-CustomBackground#38]
Sorry for creating an issue just because of this but "Once installed upload image into the local storage" is quite vague.
What location exactly do I need to put the file in?
I tried `/` `~/` and `~/.octoprint` but nothing changed so far.

**Comment by jneilliii** [comment]
Literally upload the image like it was a gcode file, ot the local side not the SD card side...

**Comment by JustCryen** [comment]
Okay, got it.
For anyone trying to do it via ssh, it doesn't work.
The directory is `~/.octoprint/uploads` but for some reason it doesn't catch it.
I actually didn't know that moving a file onto Octoprint tab uploads it so it didn't occur to me at first ;P

**Comment by jneilliii** [comment]
yeah, you shouldn't copy fies direct to uploads, if anything you should copy to the watched folder instead, that way the processors that exist for file handling would take care of it.

**Comment by JustCryen** [comment]
Actually, updating this once again for those interested. 
I've found a way to use ssh for it.
copy the file to `~/.octoprint/data/custombackground` and name it uploaded.png (Leave the extension as your original file, keep in mind the supported file types)
