### ISSUE TITLE
Overrides Octoprint Logo Appearance settings back to green

### ISSUE THREAD

**Issue by Ocelot08** [jneilliii/OctoPrint-CustomBackground#39]
When I have this plugin activated, the top left Octoprint tentacle logo resets to the default green, rather than basing it on the "Appearance" setting (mine usually set to black)

**Comment by jneilliii** [comment]
Ah, probably because the plugin has the ability to replace that icon as well. If you download the image used for black, name it icon.png and upload it to octoprint like a gcode file it will replace the green one for you.

**Comment by Ocelot08** [comment]
ah, perfect! thanks

**Comment by BSKFeralLycan** [comment]
By download the image used for black do you mean saving the color tile as a ,png?

**Comment by jneilliii** [comment]
With the plugin disabled and operating OctoPrint normally, changes the appearance setting to black. Right click the icon and save as image with the name icon.png. enable the plugin and then upload the icon.png file.
