### ISSUE TITLE
picture bad size

### ISSUE THREAD

**Issue by qpens** [jneilliii/OctoPrint-CustomBackground#4]
picture not resizing  to graph size or too big or too small

**Comment by jneilliii** [comment]
I may consider automatically resizing images on upload once I have that part of the plugin developed.  Until then there are plenty of options to resize your photos prior.

**Comment by jneilliii** [comment]
This will be fixed on next release by adding background-size css property to the temp_graph div.

**Comment by qpens** [comment]
Cool! Any chance for using path directly from sd card? I ask this question because I'm running gif and octoprint is blocking gifs from upload

**Comment by jneilliii** [comment]
I'll have to add gif to the allowed extension list.

**Comment by jneilliii** [comment]
I've added gif support in 0.5.0.

**Comment by qpens** [comment]
It's working thanks. Still showing error but uploaded successful
