### ISSUE TITLE
IMAGE CENTERING-SIZE

### ISSUE THREAD

**Issue by ACIDIKPUKE** [jneilliii/OctoPrint-CustomBackground#40]
jneilliii,

Would you be so kind as to provide specifications for the image size required to "contain" or "cover" the graph area. Most images do not properly cover the graph area properly. If you provide size specifications used by the original "Octopi" logo I can then resize my image in photoshop for a perfect fit.

Thanks.

**Comment by jneilliii** [comment]
Maybe you missed the settings?

**Comment by jneilliii** [comment]
The plugin's settings. It has options for sizing the image for you. If you are just looking for what the default resolution (it can change if you have other plugins installed like Consolidated Tabs, UI Customizer, Themeify, etc.) is that value is 588x350.
