### ISSUE TITLE
Instructions are a bit vague for custom logo

### ISSUE THREAD

**Issue by jh20001** [jneilliii/OctoPrint-CustomBackground#41]
It said uploaded via the interface to local, but it doesn't mention where. Uploaded from interface tells me that somewhere within Octoprint there is an upload field. However, gave up as I never found it. Instead, I just ssh'd into the Pi, found the directory where the images were, dumped some of mine in there, and then added a bunch of lines to the code to add them to the list.

**Comment by jneilliii** [comment]
Or, you just use the Upload button as if you were uploading a gcode file.

**Comment by jh20001** [comment]
I see now. Thank you!
