### ISSUE TITLE
Custom 10% Gray or Transparent Backgrounds Don't Fill Graph...

### ISSUE THREAD

**Issue by puterboy** [jneilliii/OctoPrint-CustomBackground#42]
I turned on the 10% gray background but it only fills the central sqare portion of the graph leaving a large dark (background color) "picture frame" around it -- which looks really bad and wrong visually.
I am using 'cover' as my image fill which I would have thought would stretch the background to fill the space.
(I am using 'center center' for the background position)

Perhaps this is the expected behavior but it looks awful :)

**Comment by jneilliii** [comment]
will investigate. these changes were contributed by someone else, so will have to see if the image sizes just don't match up to the actual available size of the graph or not.

**Comment by jneilliii** [comment]
As mentioned in https://github.com/jneilliii/OctoPrint-FloatingNavbar/issues/14 I think this is actually a bug with PlotlyTempGraph plugin. 

![image](https://user-images.githubusercontent.com/5249455/184044330-2abbe58b-1ff4-4738-ab72-9c4091dd17f9.png)
