### ISSUE TITLE
Grid and Axis colors are not responding

### ISSUE THREAD

**Issue by puterboy** [jneilliii/OctoPrint-CustomBackground#43]
I tried setting the grid and axis colors to various combinations such as:
```
rgba(255,0,0,.05)
rgba(0,255,0,.05)
rgba(0,0,255,.05)
```
But nothing seemed to have any affect.
I tried this in both 'transparent' and '10% fill' background modes.

Am I missing something obvious?

**Comment by jneilliii** [comment]
will investigate

**Comment by jneilliii** [comment]
Similar to your other issue relative to scaling of the background, this is actually another plotlytempgraph plugin conflict and it seems maybe Consolidated Tabs plugin too. These custom background options only pertain to the default temperature graph. 

![image](https://user-images.githubusercontent.com/5249455/184045367-0284922d-9386-42e3-94b3-96029ff67c32.png)
