### ISSUE TITLE
Doesn't seem to work with UI Customizer

### ISSUE THREAD

**Issue by ackerthehacker2** [jneilliii/OctoPrint-CustomBackground#45]
I can't get this work .. I have uploaded my jpg and its available a /home/octoprint/.data/custombackground/uploaded.jpg but it never displays it.
![Screenshot 2023-03-06 at 6 33 18 AM](https://user-images.githubusercontent.com/38703791/223112149-2b0962a1-71c5-43aa-ba4f-a36aae0376d5.jpg)
[octoprint-systeminfo-20230306063340.zip](https://github.com/jneilliii/OctoPrint-CustomBackground/files/10898206/octoprint-systeminfo-20230306063340.zip)

**Comment by jneilliii** [comment]
What version of plotly temp graph are you using?

**Comment by ackerthehacker2** [comment]
> What version of plotly temp graph are you using?

How do you do that?

**Comment by jneilliii** [comment]
Look in software update settings or plugin manager if OctoPrint.

**Comment by ackerthehacker2** [comment]
For some reason it didn't update the package ...once I updated it with plotly temp, it worked fine.
