### ISSUE TITLE
Custom Background

### ISSUE THREAD

**Issue by DanCantrell** [jneilliii/OctoPrint-CustomBackground#46]
Trying to set a custom image on the temperature panel and I followed your directions like you said as far as I'm aware but when the page reloads I get nothing..

**Comment by jneilliii** [comment]
Any errors in your browser's developer tools console tab (F12 on your keyboard)? Check OctoPrint log too for any potential errors during upload of the image.

**Comment by DanCantrell** [comment]
Is this helpful?

**Comment by DanCantrell** [comment]
Oh wow.  I just disabled UI Customizer and it worked.  Maybe some compatibility issue?

**Comment by jneilliii** [comment]
Ah that plugin has an option to hide the image. Disable that option and you should see it.

**Comment by DanCantrell** [comment]
Doh!  Yep, that worked. I sure do appreciate your help and work. I'm pretty new in all of this but I've been watching you and the other heavyweights from afar. Just last week Paul helped me get all 3 of my printers going with webcams using his Octoprint_deploy. I didn't have any problem getting the functionality of the printers going but the webcams was a monster . To me at least. Lol.. Have been working on it for weeks. But like I said, I really appreciate all of you.

**Comment by jneilliii** [comment]
Glad to help when I can.
