### ISSUE TITLE
Image upload failed

### ISSUE THREAD

**Issue by triton-nereide** [jneilliii/OctoPrint-CustomBackground#47]
Hi jeneilliii,

I use your octoprint customBackground Plug for many years now, I love it, however, now @ my latest install (Octoprint 1.9.1 (with new camstack) Octopi 1.0 octodash 2.3.x (latest) it failed to upload an .png image as background for the temperature field.
I started to investigate the reason - however, it´s conflicting with UI Customizer, as soon as I deactivate UI customizer, the image shows up correctly where and how it should. The same stays when activating Themeify (which is half abandoned, sadly), but as soon as I activate UI Customizer the image disapears, upload fails - mainly I think because it´s already there, just somehow hidden.
UI Customizer offers a nice way to layout the screen, and CustomBackground is a must for me...
Do you think something can be done about this? Should I contact UI Costomizer team?

regards, C

**Comment by jneilliii** [comment]
There's an option in UI customizer to hide the background image. If you disable that option you should see the custom one you uploaded.

**Comment by triton-nereide** [comment]
O.K. thanx, I ´ve found it, and it works...
